feat: env detail
servant-developers/CatD pull request #8
Opened 2020-09-08 14:35 UTC by groovypark

reference: https://blog.harveydelaney.com/creating-your-own-react-component-library/

2020-09-08 14:44 UTC, naamoonoo requested changes
`.vscode` 폴더는 저희가 프리티어 세팅을 쓰는데, 저장하면 코드 포멧이 맞춰지도록 해 놓은 것 입니다 ㅎㅎ지우시 말아주세욤

2020-09-08 14:44 UTC, naamoonoo commented on package.json
> +  "module": "dist/index.es.js",
아항 rollup에서 이렇게 분리를 했어야 하는군욤. 배워갑니당 헿

2020-09-08 14:44 UTC, naamoonoo commented on src/Button/Button.stories.tsx
> -import { Button, ButtonProps, Size } from './Button';
앞으로 안쓰는건 제깍제깍 지우겠습니다... 영제님 콘솔로그 안지운게 더 신기하넴...ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2020-09-08 14:44 UTC, naamoonoo commented on tsconfig.json
> +    "lib": ["es6", "dom", "es2016", "es2017"],
오홍 이게 무슨 차이인지 설명해주실수있을까욤?

2020-09-08 23:08 UTC, naamoonoo commented
.vscode의 settings.json 복구 및 업데이트 + .gitignore에서 .vscode삭제 했습니당

2020-09-08 23:08 UTC, merged

2020-09-11 08:21 UTC, groovypark commented on tsconfig.json
> +    "lib": ["es6", "dom", "es2016", "es2017"],
@naamoonoo 대부분이 아래처럼 설정하더라고요
ES5의 기본 값: dom, es5, scripthost
ES6의 기본 값: dom, dom.iterable, es6, scripthost
이거인데
작성한 코드나, 코드에서 참조하는 모듈들(node_modules)에서 ES6를 사용하려면 es6 라는 라이브러리를 위처럼 정의해서 라이브러리 인젝션을 해줘야 한대용